version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - hf_cache:/root/.cache/huggingface     # كاش للموديلات
    networks: [net]
    expose: ["8000"]

  web:
    build: ./web
    depends_on: [api]
    networks: [net]
    expose: ["80"]

  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [web, api]
    ports:
      - "80:80"
    networks: [net]

networks:
  net:

volumes:
  db_data:
  hf_cache:
